services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: facturas_app_compose
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://postgres:mysecretpassword@localhost:5432/snapclaim"
      PORT: "3000" # The port Next.js standalone server will listen on inside the container
      NODE_ENV: "production"
      # For NextAuth.js if you add it later:
      # NEXTAUTH_URL: "http://localhost:3000" # URL of your app
      # NEXTAUTH_SECRET: "your_super_secret_nextauth_value" # Generate a strong secret
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    networks:
      - facturas_network
    # Optional: For development, you might mount volumes for hot-reloading
    # but for a production-like build, relying on the Dockerfile build is better.
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next

networks:
  facturas_network:
    driver: bridge
